import { chromium } from 'playwright-core';
const B = process.env.B || 'https://curvesmith.vercel.app';
const out = '/tmp/qa2/live';
const browser = await chromium.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const logs = [];
page.on('console', (m) => m.type() === 'error' && logs.push('console: ' + m.text().slice(0, 200)));
page.on('pageerror', (e) => logs.push('pageerror: ' + e.message));
const snap = async (n) => { await page.screenshot({ path: `${out}-${n}.png` }); console.log('shot', n); };
const toasts = async () => (await page.locator('.toast').allInnerTexts()).map((t) => t.replace(/\s+/g, ' ').slice(0, 160));
await page.goto(B + '/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(3000);
await snap('1-studio');
await page.click('text=Connect');
await page.waitForTimeout(800);
await page.click('.wallet-opt:has-text("Burner")');
await page.waitForTimeout(2500);
console.log('toasts early', await toasts());
await page.waitForTimeout(8000);
console.log('toasts after connect', await toasts());
await snap('2-funded');
console.log('wallet btn', await page.locator('.wallet-btn').innerText().catch(() => 'none'));
await page.goto(B + '/#/preset/HgvGXfabwFoozaDWYnp8MNY4csRTbutyS97N78uofoa5', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(6000);
await snap('3-preset');
await page.click('button:has-text("Launch")');
await page.waitForTimeout(800);
const inputs = page.locator('.modal input');
await inputs.nth(0).fill('Judge Test');
await inputs.nth(1).fill('JTST');
await inputs.nth(2).fill('0.1');
await snap('4-launchmodal');
await page.locator('.modal button.btn.primary.block').click();
await page.waitForTimeout(1500);
console.log('btn text', await page.locator('.modal button.btn.primary.block').innerText().catch(()=>'gone'), await toasts());
for (let i = 0; i < 40; i++) {
  await page.waitForTimeout(1500);
  if (page.url().includes('#/pool/')) break;
}
console.log('url after launch', page.url());
console.log('toasts', await toasts());
await page.waitForTimeout(6000);
await snap('5-pool');
const amt = page.locator('input[type=number]').first();
await amt.fill('0.1');
await page.waitForTimeout(2500);
await snap('6-quote');
await page.click('button.btn.primary.block.lg');
await page.waitForTimeout(15000);
console.log('toasts after buy', await toasts());
await snap('7-bought');
console.log(JSON.stringify(logs.slice(0, 20), null, 1));
await browser.close();
