import { chromium } from 'playwright-core';
import fs from 'node:fs';
const B = 'https://curvesmith.vercel.app';
const burner = fs.readFileSync('/tmp/qa2/burner.json', 'utf8');
const browser = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.addInitScript((b) => { localStorage.setItem('curvesmith:burner', b); localStorage.setItem('curvesmith:wallet', 'Burner wallet'); localStorage.setItem('curvesmith:autofund:CvVxJC6ABCw3781neD2KKzH6c8aH2RztkNkvd8yW7bfK', '1'); }, burner);
const page = await ctx.newPage();
const logs = [];
page.on('pageerror', (e) => logs.push('pageerror: ' + e.message));
page.on('console', (m) => m.type() === 'error' && logs.push('console: ' + m.text().slice(0, 200)));
const toasts = async () => (await page.locator('.toast').allInnerTexts()).map((t) => t.replace(/\s+/g, ' ').slice(0, 200));
await page.goto(B + '/#/atlas', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(3000);
await page.locator('a.btn.sm:has-text("Fork")').nth(1).click();
await page.waitForTimeout(9000);
console.log('fork toasts', await toasts());
await page.screenshot({ path: '/tmp/qa2/fork-1.png' });
await page.click('button:has-text("Forge preset on devnet")');
await page.waitForTimeout(800);
await page.fill('.modal input', 'Forked from a mainnet launchpad, tuned');
await page.click('.modal button:has-text("Sign and publish")');
for (let i = 0; i < 30; i++) { await page.waitForTimeout(1500); if (await page.locator('.modal :text("Forged ✓")').count()) break; }
console.log('publish toasts', await toasts());
await page.screenshot({ path: '/tmp/qa2/fork-2.png' });
console.log(JSON.stringify(logs.slice(0, 10)));
await browser.close();
